apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app-a-predictkube-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: app-a
    kind: Deployment
  pollingInterval: 10                # Verifica a cada 10 segundos
  cooldownPeriod: 120                # 2 minutos de cooldown
  minReplicaCount: 1                 # Mínimo 1 réplica
  maxReplicaCount: 10                # Máximo 10 réplicas
  triggers:
  - type: predictkube
    metadata:
      predictHorizon: "2h"                    # Prediz para as próximas 2 horas
      historyTimeWindow: "7d"                 # Usa 7 dias de dados históricos
      prometheusAddress: "http://prometheus-service.default.svc.cluster.local:9090"  # Endereço completo do Prometheus
      query: "sum(rate(app_requests_total{job=\"app-a\"}[2m]))"  # Query para métricas de request rate
      queryStep: "2m"                        # Intervalo de 2 minutos para queries
      threshold: "10"                        # Threshold para começar a escalar
      activationThreshold: "5"               # Threshold para ativar o scaler
    authenticationRef:
      name: predictkube-trigger-auth
