apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'app-a'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: app-a
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: metrics
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: ${1}:8080

      - job_name: 'keda-operator'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - keda-system
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: keda-operator
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: http-metrics
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: ${1}:8080
        scrape_interval: 30s
        metrics_path: /metrics

      - job_name: 'keda-metrics-apiserver'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - keda-system
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: keda-operator-metrics-apiserver
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "8080"
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: ${1}:8080
        scrape_interval: 30s
        metrics_path: /metrics
